name: coffee_pos
description: POS Coffee Shop Offline

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Utils
  intl: ^0.19.0
  crypto: ^3.0.3
  uuid: ^4.4.0
  shared_preferences: ^2.3.2

  # Image
  image_picker: ^1.1.2

  # UI
  google_fonts: ^6.2.1

  esc_pos_utils_plus: ^2.0.4

  # ✅ Bluetooth - pakai dart native
  flutter_blue_plus: ^1.35.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ✅ Hanya package yang wajib untuk build
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

    # ✅ Tambah untuk Google Drive sync
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  connectivity_plus: ^6.1.4
  http: ^1.3.0

  # ✅ Tambah untuk export
  pdf: ^3.11.1
  printing: ^5.13.3
  excel: ^4.0.6
  open_file: ^3.5.7

  # ✅ Tambah file picker
  file_picker: ^8.1.7

# ✅ Tambah konfigurasi icon
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4E342E"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
